/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as UsermandateImport } from './routes/usermandate'
import { Route as MandatesImport } from './routes/mandates'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const UsermandateRoute = UsermandateImport.update({
  id: '/usermandate',
  path: '/usermandate',
  getParentRoute: () => rootRoute,
} as any)

const MandatesRoute = MandatesImport.update({
  id: '/mandates',
  path: '/mandates',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/mandates': {
      id: '/mandates'
      path: '/mandates'
      fullPath: '/mandates'
      preLoaderRoute: typeof MandatesImport
      parentRoute: typeof rootRoute
    }
    '/usermandate': {
      id: '/usermandate'
      path: '/usermandate'
      fullPath: '/usermandate'
      preLoaderRoute: typeof UsermandateImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mandates': typeof MandatesRoute
  '/usermandate': typeof UsermandateRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mandates': typeof MandatesRoute
  '/usermandate': typeof UsermandateRoute
  '/users': typeof UsersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/mandates': typeof MandatesRoute
  '/usermandate': typeof UsermandateRoute
  '/users': typeof UsersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/mandates' | '/usermandate' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/mandates' | '/usermandate' | '/users'
  id: '__root__' | '/' | '/about' | '/mandates' | '/usermandate' | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MandatesRoute: typeof MandatesRoute
  UsermandateRoute: typeof UsermandateRoute
  UsersRoute: typeof UsersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MandatesRoute: MandatesRoute,
  UsermandateRoute: UsermandateRoute,
  UsersRoute: UsersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/mandates",
        "/usermandate",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/mandates": {
      "filePath": "mandates.tsx"
    },
    "/usermandate": {
      "filePath": "usermandate.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
